<?php /* @var $this Codex_Yapital_Block_System_Config_Storage_Credentials_Notification */ ?>

<?php echo $this->getButtonHtml() ?><span class="validation-indicator no-display" id="<?php echo $this->getConfigPath(); ?>_notification_span"><img
        alt="Synchronize" style="margin:0 5px" src="<?php echo $this->getSkinUrl('images/process_spinner.gif')
?>"/></span><span id="<?php echo $this->getConfigPath(); ?>_notification_message_span"></span>
<input type="hidden" id="<?php echo $this->getConfigPath(); ?>_validation-input" class="required-validation no-display"/>

<div style="margin-top: 6px">
    <?php echo $this->getButtonUnregisterHtml(); ?>
</div>