<?php /* var $this Codex_Yapital_Block_System_Config_Storage_Credentials_Validate */ ?>

<script type="text/javascript">
    //<![CDATA[
<!--    Validation.add('required-validation', '--><?php //echo $this->__('Validation is required.') ?><!--', function () {-->
<!--        storage = getConnectionName(-->
<!--                $('payment_yapital_standard_sandbox_client_id').value,-->
<!--                $('payment_yapital_standard_sandbox_secret_key').value-->
<!--        );-->
<!---->
<!--        console.log(allowedNotifications);-->
<!---->
<!--        return allowedNotifications.include(storage);-->
<!--    });-->

    defaultValues = [];
    defaultValues['payment_yapital_standard_sandbox_client_id'] = $('payment_yapital_standard_sandbox_client_id').value;
    defaultValues['system_media_storage_configuration_media_database'] = $('payment_yapital_standard_sandbox_secret_key').value;

    allowedNotifications = [];
    addAllowedStorage(
            $('payment_yapital_standard_sandbox_client_id').value,
            $('payment_yapital_standard_sandbox_secret_key').value
    );

    function getConnectionName(storageType, connection) {
        return storageType + '_' + connection;
    }

    function addAllowedStorage(storageType, connection) {
        var storage = getConnectionName(storageType, connection);

        if (storage != getConnectionName('', '') && !allowedNotifications.include(storage)) {
            allowedNotifications.push(storage);
        }
    }

    function checkButtonState(event) {
        var element = Event.element(event);

        var defaultStorage = getConnectionName(
                defaultValues['payment_yapital_standard_sandbox_client_id'],
                defaultValues['payment_yapital_standard_sandbox_secret_key']
        );

        storage = getConnectionName(
                $('payment_yapital_standard_sandbox_client_id').value,
                $('payment_yapital_standard_sandbox_secret_key').value
        );

        if (defaultStorage != storage) {
            enableValidateButton();
        } else {
            disableValidateButton();
        }
    }

    function enableStorageSelection() {
        $('payment_yapital_standard_sandbox_client_id').enable('enabled');
        $('payment_yapital_standard_sandbox_secret_key').enable('enabled');
    }

    function disableStorageSelection() {
        $('payment_yapital_standard_sandbox_client_id').disable('disabled');
        $('payment_yapital_standard_sandbox_secret_key').disable('disabled');
    }

    function enableValidateButton() {
        Form.Element.enable('validate_button');
        $('validate_button').removeClassName('disabled');
    }

    function disableValidateButton() {
        Form.Element.disable('validate_button');
        $('validate_button').addClassName('disabled');
    }

    Event.observe(window, 'load', function () {
        //disableStorageSelection();
        //disableValidateButton();
        //checkStatus();
    });
    $('payment_yapital_standard_sandbox_client_id').observe('change', checkButtonState);
    $('payment_yapital_standard_sandbox_secret_key').observe('change', checkButtonState);

    function yapitalCheckStatus() {

    }

    function validateSandboxYapital() {
        //var advice = Validation.getAdvice('required-validation', $('synchronize-validation-input'));
        //if (advice) {
        //    advice.hide();
        //}
        console.log("validateYapital()");

        params = {
            shop_id   : 1,
            client_id :$('payment_yapital_standard_sandbox_client_id').value,
            secret_key:$('payment_yapital_standard_sandbox_secret_key').value
        };

        $('credentials_sandbox_message_span').addClassName('no-display');
        $('credentials_sandbox_span').removeClassName('no-display');

        new Ajax.Request('<?php echo $this->getAjaxValidateUpdateUrl() ?>', {
            parameters  :params,
            loaderArea  :false,
            asynchronous:false,
            onSuccess   :function (transport) {
                var response;

                response = eval('(' + transport.responseText + ')');
                console.log(response);
                if (false == response.has_errors) {
                    // no errors: it works!
                    disableValidateButton();
                } else {
                    // TODO ERROR
                }

                allowedNotifications.push(getConnectionName(
                        $('payment_yapital_standard_sandbox_client_id').value,
                        $('payment_yapital_standard_sandbox_secret_key').value
                ));

                $('credentials_sandbox_span').addClassName('no-display');
                $('credentials_sandbox_message_span').removeClassName('no-display');
                $('credentials_sandbox_message_span').update(response.message);
            },

            onFailure:function (transport) {
                $('credentials_sandbox_span').addClassName('no-display');
                $('credentials_sandbox_message_span').removeClassName('no-display');
                $('credentials_sandbox_message_span').update('<?php echo $this->__('Internal error during validation.') ?>');
            }

        });

        //window.setTimeout('yapitalCheckStatus()', 2011);

        //disableStorageSelection();
        //disableValidateButton();
        enableValidateButton();
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?><span class="validation-indicator no-display" id="credentials_sandbox_span"><img
        alt="Synchronize" style="margin:0 5px" src="<?php echo $this->getSkinUrl('images/process_spinner.gif')
?>"/></span><span id="credentials_sandbox_message_span"></span>
<input type="hidden" id="validation-input" class="required-validation no-display"/>
