<?php /** @var Codex_Yapital_Block_System_Config_Storage_Credentials_Update $this */ ?>

<?php echo $this->getButtonHtml() ?>
<span class="update-indicator no-display" id="<?php echo $this->getConfigPath(); ?>_update_span"><img
        alt="Synchronize" style="margin:0 5px" src="<?php echo $this->getSkinUrl('images/process_spinner.gif')
    ?>"/></span><span id="<?php echo $this->getConfigPath(); ?>_update_message_span"></span>
<input type="hidden" id="<?php echo $this->getConfigPath(); ?>_update-input"
       class="required-update no-display"/>
