<?php /* @var $this Codex_Yapital_Block_System_Config_Storage_Credentials_Validate */ ?>

<script type="text/javascript">
    var <?php echo $this->getConfigPath(); ?>_yapitalConfig = new YapitalConfig( <?php echo $this->getJSConfig() ?> );
</script>

<?php echo $this->getButtonHtml() ?><span class="validation-indicator no-display" id="<?php echo $this->getConfigPath(); ?>_validation_span"><img
        alt="Synchronize" style="margin:0 5px" src="<?php echo $this->getSkinUrl('images/process_spinner.gif')
?>"/></span><span id="<?php echo $this->getConfigPath(); ?>_validation_message_span"></span>
<input type="hidden" id="<?php echo $this->getConfigPath(); ?>_validation-input" class="required-validation no-display"/>
