<?php /** @var Codex_Yapital_Block_System_Config_Head $this */ ?>
<img src="<?php echo $this->getSkinUrl('images/codex/yapital/yapital150x39.png') ?>" />

<p>
    <?php echo $this->helper('yapital')->__('Please fill out the information below.') ?>
    <?php echo $this->helper('yapital')->__(
        'Read this documentation of tests you need to run before going online:'
    ) ?>
    <a href="<?php echo Mage::getUrl('yapital/standard/documentation') ?>">
        <?php echo $this->helper('yapital')->__('Documentation') ?>
    </a>
</p>
