<p>
    <?php echo $this->__('In this section you could edit all Yapital related configuration parameter and you could enable the Yapital payment. In order to activate Yapital please do as follows:')?>
</p>

<ol style="list-style: lower-roman; margin-left: 2em;">
    <li><?php echo $this->__('Set enabled to "YES"'); ?></li>
    <li><?php echo $this->__('Enter a Title (will appear on the customer facing Web-site) and should contain "Yapital payment"'); ?></li>
    <li><?php echo $this->__('Paid order status has to be set to "processing". This will be the internal status after the customer paid with Yapital'); ?></li>
    <li><?php echo $this->__('Set "Use this credentials" to "Live"'); ?></li>
    <li><?php echo $this->__('Next copy/paste your Shop-ID, Client-Id and your Secret Key'); ?></li>
    <li><?php echo $this->__('Click on "Validate" to check the credentials given'); ?></li>
    <li><?php echo $this->__('Click on "Generate a new secret", a new secret will appear in the field'); ?></li>
    <li><?php echo $this->__('Enter some random chars into the "Yapital Notification Id" and press "Register notification"'); ?></li>
    <li><?php echo $this->__('Click on "Register notification" to register the notification'); ?></li>
    <li><?php echo $this->__('Click on "Save Config" on top of the screen'); ?></li>
</ol>

<hr />

<p>
    <?php echo $this->__('Checks: Please open your shop and go shopping. Choose the payment  method "Yapital" and pay with your Yapital account. In the backend you should see your transaction with the Paid order status "processing" now.'); ?>
</p>

<p>
    <?php echo $this->__('More information (including the setup of a test-connection to a Yapital test-system) could be found in the delivered plugin-documentation.'); ?>
</p>
