<h2><?php echo $this->__('A problem occurred') ?></h2>

<?php echo $this->__(
    'We are sorry!
    It was not possible to receive your payment from yapital.
    Therefor we canceled your order.
    You can try it again or choose another payment method.'
) ?>

<div class="a-center">
    <a  href="<? echo Mage::getUrl('checkout/cart') ?>">
        <?php echo $this->__('Back to cart') ?>
    </a>
</div>
