<?php /* @var $this Codex_Yapital_Block_Standard_Iframe */ ?>
<div id="yapital-widget-container-id"></div>
<script src="<?php echo $this->getApiIFrameScript(); ?>"></script>
<script>
    (function (window) {
        var transactionId = "<?php echo $this->getTransactionId(); ?>";
        window.__yapital_init_widget(transactionId, "<?php echo $this->getApiIFrameScript(); ?>",
                                     "yapital-widget-container-id");
    })(window);
</script>
