<?php
/**
 * Defines the Item datatype for the Yapital API
 *
 *
 * PHP version 5
 *
 *
 * @category   Datatype
 * @package    Codex_Yapital_Model_Datatype
 * @copyright  2013 Code-X GmbH
 * @link       http://code-x.de
 * @since      File available since Release 0.1.0
 */

/**
 * The Item type specifies the details of a Web shop item.
 *
 *
 *
 * @category   Datatype
 * @package    Codex_Yapital_Model_Datatype
 * @copyright  2013 Code-X GmbH
 * @version    Release: @package_version@
 * @link       http://code-x.de
 * @since      Class available since Release 0.1.0
 */
class Codex_Yapital_Model_Datatype_Item extends Codex_Yapital_Model_Datatype_Abstract
    implements Codex_Yapital_Model_Datatype_Interface
{

    /**
     * The item public ID generated by Yapital.
     *
     * @var Codex_Yapital_Model_Datatype_YapitalPublicId
     */
    protected $_itemId;

    /**
     * The item name, specified by the client side (the Web shop).
     *
     * @var string
     */
    protected $_itemTitle;

    /**
     * The item price, specified by the client side (the Web shop).
     *
     * @var float
     */
    protected $_itemPrice;

    /**
     * The tax added to the item price, specified by the client side (the Web shop).
     *
     * @var float
     */
    protected $_itemTaxAmountIncluded;

    /**
     * The minimum age in years a Web shop customer must be to buy the item.
     *
     * @var int unsigned
     */
    protected $_itemMinAge;

    /**
     * The total price of the item without a tax (net value).
     *
     * @var float
     */
    protected $_totalItemPrice;

    /**
     * The total price of the item including a tax (gross value).
     *
     * @var float
     */
    protected $_totalItemTaxIncluded;

    /**
     * Item ID provided by the Web shop that owns it.
     *
     * @var string
     */
    protected $_shopItemId;

    /**
     * Number of items.
     *
     * @var int positive
     */
    protected $_quantity;

    /**
     * This field can be used by a shop to provide any custom data, e.g. a description
     *
     * @var array
     */
    protected $_merchantItems = array();

    /**
     * @param \Codex_Yapital_Model_Datatype_YapitalPublicId $itemId
     */
    public function setItemId ( $itemId )
    {
        $this->_itemId = $itemId;
        return $this;
    }

    /**
     * @return \Codex_Yapital_Model_Datatype_YapitalPublicId
     */
    public function getItemId ()
    {

        return $this->_itemId;
    }

    /**
     * @param int $itemMinAge
     */
    public function setItemMinAge ( $itemMinAge )
    {

        $this->_itemMinAge = $itemMinAge;

        return $this;
    }

    /**
     * @return int
     */
    public function getItemMinAge ()
    {

        return (int) $this->_itemMinAge;
    }

    /**
     * @param float $itemPrice
     */
    public function setItemPrice ( $itemPrice )
    {

        $this->_itemPrice = $itemPrice;

        return $this;
    }

    /**
     * @return float
     */
    public function getItemPrice ()
    {

        return (float) $this->_itemPrice;
    }

    /**
     * @param float $itemTaxAmountIncluded
     */
    public function setItemTaxAmountIncluded ( $itemTaxAmountIncluded )
    {

        $this->_itemTaxAmountIncluded = $itemTaxAmountIncluded;

        return $this;
    }

    /**
     * @return float
     */
    public function getItemTaxAmountIncluded ()
    {

        return (float) $this->_itemTaxAmountIncluded;
    }

    /**
     * @param string $itemTitle
     */
    public function setItemTitle ( $itemTitle )
    {

        $this->_itemTitle = $itemTitle;

        return $this;
    }

    /**
     * @return string
     */
    public function getItemTitle ()
    {

        return $this->_itemTitle;
    }

    /**
     * @param array $merchantItems
     */
    public function setMerchantItems ( $merchantItems )
    {

        $this->_merchantItems = $merchantItems;

        return $this;
    }

    /**
     * @return array
     */
    public function getMerchantItems ()
    {

        return $this->_merchantItems;
    }

    /**
     * @param int $quantity
     */
    public function setQuantity ( $quantity )
    {

        $this->_quantity = $quantity;

        return $this;
    }

    /**
     * @return int
     */
    public function getQuantity ()
    {

        return (int) $this->_quantity;
    }

    /**
     * @param string $shopItemId
     */
    public function setShopItemId ( $shopItemId )
    {

        $this->_shopItemId = $shopItemId;

        return $this;
    }

    /**
     * @return string
     */
    public function getShopItemId ()
    {

        return $this->_shopItemId;
    }

    /**
     * @param float $totalItemPrice
     */
    public function setTotalItemPrice ( $totalItemPrice )
    {

        $this->_totalItemPrice = $totalItemPrice;

        return $this;
    }

    /**
     * @return float
     */
    public function getTotalItemPrice ()
    {

        return (float) $this->_totalItemPrice;
    }

    /**
     * @param float $totalItemTaxIncluded
     */
    public function setTotalItemTaxIncluded ( $totalItemTaxIncluded )
    {

        $this->_totalItemTaxIncluded = $totalItemTaxIncluded;

        return $this;
    }

    /**
     * @return float
     */
    public function getTotalItemTaxIncluded ()
    {

        return (float) $this->_totalItemTaxIncluded;
    }

    function importItem ( Mage_Sales_Model_Order_Item $item )
    {

        $name = $item->name;
        /// @todo min age -> config
        $minAge     = 0;
        $shopItemId = $item->item_id;

        $this->setShopItemId($shopItemId);
        $this->setItemTitle($name);
        $this->setItemMinAge($minAge);

        /* @todo right fields selected from Order_Item? */
        $this->setItemPrice($item->getBasePrice());
        $this->setItemTaxAmountIncluded($item->getTaxAmount());

        $this->setTotalItemPrice($item->getPrice());
        $this->setTotalItemTaxIncluded($item->getPriceInclTax());

        $this->setQuantity($item->getQtyOrdered());

        return $this;
    }


    function getData ()
    {

        return array(
            "item_title"               => $this->getItemTitle(),
            "item_price"               => (float) $this->getItemPrice(),
            "item_tax_amount_included" => (float) $this->getItemTaxAmountIncluded(),
            "item_min_age"             => $this->getItemMinAge(),
            "total_item_price"         => (float) ($this->getItemPrice()),
            "total_item_tax_included"  => (float) ($this->getTotalItemTaxIncluded()),
            "shop_item_id"             => $this->getShopItemId(),
            "quantity"                 => $this->getQuantity(),
        );
    }
}
