<?php
/**
 * Created by PhpStorm.
 * User: mike
 * Date: 2/20/14
 * Time: 3:14 PM
 */

class Codex_Yapital_Model_Api_BasketCollection extends Varien_Data_Collection
{
    public function api()
    {
        Codex_Yapital_Model_Log::log("Sending BasketTransaction");

        /* @var $basketTransaction Codex_Yapital_Model_DataType_BasketsTransaction */
        $basketTransaction = Mage::getModel('yapital/datatype_basketstransaction');
        $basketTransaction->importOrder($order);


        $url      = '/shops/' . $this->_getConfig()->getYapitalShopId() . '/basket_transaction';
        $response = $this->_send($url, $basketTransaction);

        /**
         * @var $shopRestResponse Codex_Yapital_Model_Datatype_Shoprestresponse
         */
        $shopRestResponse = Mage::getModel("yapital/datatype_shoprestresponse");
        $shopRestResponse->importRawResponse($response);

        $order_transaction = $this->getOrderTransaction();
        $order_transaction->importShopRestResponse($order, $shopRestResponse);

        $order_transaction->save();

        return $shopRestResponse;
    }

    public function loadData($printQuery = false, $logQuery = false)
    {

        return parent::loadData($printQuery, $logQuery); // TODO: Change the autogenerated stub
    }

}
