<?php /* var $this Codex_Yapital_Block_System_Config_Storage_Credentials_Validate */ ?>

<script type="text/javascript">
    //<![CDATA[
    function yapitalGenerateNotificationSecret() {
        var uniq = Math.floor(Math.random() * 0xF + 10).toString(36);
        uniq += Math.floor(Math.random() * 0x100000000).toString(36);
        uniq += Math.floor(Math.random() * 0x1000).toString(36);
        uniq += Math.floor(Math.random() * 0x1000).toString(36);
        uniq += Math.floor(Math.random() * 0x1000).toString(36);

        return uniq;
    }

    function yapitalLiveGenerateNotificationSecret() {
        $('payment_yapital_standard_notification_secret').value = yapitalGenerateNotificationSecret();
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>
